# Generated by Django 4.1.7 on 2023-04-04 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("phone_number", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=50)),
                ("college", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=50)),
                ("years_of_experience", models.PositiveIntegerField()),
                (
                    "subjects_to_contribute",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Choose..."),
                            ("DSA", "DSA"),
                            ("Python Programming", "Python Programming"),
                            ("Unix", "Unix"),
                            ("DBMS", "DBMS"),
                            ("Computer Networks", "Computer Networks"),
                            ("Computer Architecture", "Computer Architecture"),
                            ("Operating Systems", "Operating System"),
                            ("Java Programming", "Java Programming"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "subjects_of_interest",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Choose..."),
                            ("DSA", "DSA"),
                            ("Python Programming", "Python Programming"),
                            ("Unix", "Unix"),
                            ("DBMS", "DBMS"),
                            ("Computer Networks", "Computer Networks"),
                            ("Computer Architecture", "Computer Architecture"),
                            ("Operating Systems", "Operating System"),
                            ("Java Programming", "Java Programming"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("linkedin_profile", models.URLField()),
                ("github_profile", models.URLField()),
                ("portfolio_website", models.URLField()),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
