# Generated by Django 4.1.7 on 2023-04-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Contributor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributorprofile",
            name="subjects_of_interest",
        ),
        migrations.RemoveField(
            model_name="contributorprofile",
            name="subjects_to_contribute",
        ),
    ]
