# Generated by Django 4.1.7 on 2023-04-05 20:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Contributor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
