# Generated by Django 4.1.7 on 2023-04-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Contributor", "0002_coursecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributorprofile",
            name="subjects_of_interest",
            field=models.CharField(
                blank=True,
                choices=[("DSA", "DSA"), ("DBMS", "DBMS"), ("CN", "CN")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contributorprofile",
            name="subjects_to_contribute",
            field=models.CharField(
                blank=True,
                choices=[("DSA", "DSA"), ("DBMS", "DBMS"), ("CN", "CN")],
                max_length=50,
                null=True,
            ),
        ),
    ]
