# Generated by Django 4.1.7 on 2023-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contributor", "0002_remove_contributorprofile_subjects_of_interest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributorprofile",
            name="subjects_of_interest",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Choose..."),
                    ("DSA", "DSA"),
                    ("Python Programming", "Python Programming"),
                    ("Unix", "Unix"),
                    ("DBMS", "DBMS"),
                    ("Computer Networks", "Computer Networks"),
                    ("Computer Architecture", "Computer Architecture"),
                    ("Operating Systems", "Operating System"),
                    ("Java Programming", "Java Programming"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contributorprofile",
            name="subjects_to_contribute",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Choose..."),
                    ("DSA", "DSA"),
                    ("Python Programming", "Python Programming"),
                    ("Unix", "Unix"),
                    ("DBMS", "DBMS"),
                    ("Computer Networks", "Computer Networks"),
                    ("Computer Architecture", "Computer Architecture"),
                    ("Operating Systems", "Operating System"),
                    ("Java Programming", "Java Programming"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
