# Generated by Django 4.1.7 on 2023-04-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Contributor", "0002_coursecontent"),
        ("Contributor", "0003_contributorprofile_subjects_of_interest_and_more"),
    ]

    operations = []
