# Generated by Django 4.1.7 on 2023-04-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Contributor", "0004_alter_contributorprofile_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributorprofile",
            name="isProfileComplete",
            field=models.BooleanField(default=True),
        ),
    ]
