# Generated by Django 4.1.7 on 2023-04-10 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Contributor", "0005_contributorprofile_isprofilecomplete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributorprofile",
            name="isProfileComplete",
        ),
    ]
