# Generated by Django 4.1.7 on 2023-03-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAuth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isProfileComplete",
            field=models.BooleanField(default=False),
        ),
    ]
